#!/usr/bin/env python2

import argparse
import cstyle
import os
import sys

def Main():
    """Run cstyle"""
    Parser = argparse.ArgumentParser(description='C Style Checker')
    Parser.add_argument('--config', dest='Config',
                        default=os.path.expanduser('~/.cstyle'),
                        help='configuration file')
    Parser.add_argument('FILES', metavar='FILE', nargs='+',
                        help='files to check')
    Args = Parser.parse_args()
    Errors = cstyle.CStyle(Args.Config, Args.FILES).CheckStyle()
    for Error in Errors:
        sys.stderr.write(Error)
    sys.exit(1 if len(Errors) > 0 else 0)

if __name__ == '__main__':
    Main()
